version: '3'

services:

  mqtt:
    build: ./
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config 
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/password    
    restart: always